### ISSUE TITLE
Instructions in need of update for readers

### ISSUE THREAD

**Issue by stevenlemme** [oracle-japan/ocitutorials#143]
LOGAN-8655 was opened please review and either update accordingly or remove until an update can be made. Thank You

**Comment by tniita** [comment]
Hello,
I appreciate your issue.

I have checked LOGAN-8655 and modified the policy statement on https://oracle-japan.github.io/ocitutorials/intermediates/audit-log-analytics/
Please check and close this issue if there is no problem.
Thanks,

**Comment by tniita** [comment]
close issue.
