### ISSUE TITLE
Bastionチュートリアルの構成図が正しくない

### ISSUE THREAD

**Issue by mmarukaw** [oracle-japan/ocitutorials#222]
[Bastionサービスのチュートリアル](https://oracle-japan.github.io/ocitutorials/intermediates/bastion/)の[構成図](https://oracle-japan.github.io/ocitutorials/intermediates/bastion/img1.png) で、BastionサービスがPublic Subnetの中に構成されているように表現されている。

Bastionサービスは、ユーザーが作成するSubnetには配置されないので、本来は[ドキュメント](https://docs.oracle.com/ja-jp/iaas/Content/Bastion/Concepts/bastionoverview.htm)の図のように、VCNの外に配置されるので、チュートリアルの図も修正すべき。

**Comment by shukawam** [comment]
https://github.com/oracle-japan/ocitutorials/pull/223 で修正済みのため、クローズ
